apiVersion: v1
kind: Service
metadata:
  name: discord-downloader-bot
  namespace: discord-downloader-bot
  labels:
    app: discord-downloader-bot
spec:
  type: ClusterIP
  selector:
    app: discord-downloader-bot
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
